# List of Green Valley Bible Camp camp songs we know
import random

gvbcSongBookList = {
    1: 'A Common Love',
    4: 'All in All',
    9: 'As the Deer (Old)',
   10: 'Awesome God',
   12: 'Battle Belongs to the Lord',
   13: 'Be Still and Know',
   19: 'Blue Skies and Rainbows',
   23: 'Come Let Us Sing',
   27: 'Create in Me a Clean Heart',
   29: 'Deep Down in My Heart',
   35: 'Father I Adore You',
   38: 'Freely, Freely',
   42: 'Glorify Thy Name',
   44: 'God Is So Good',
   48: 'Greatest Commands',
   52: 'Have You Seen Jesus My Lord',
   53: 'He Has Made Me Glad',
   56: 'He Is My Everything',
   58: 'He Paid a Debt',
   62: 'Hear O Israel',
   69: 'His Name Is Wonderful',
   70: 'Holy Ground',
   80: 'Humble Yourself',
   82: 'I Am Mine Nomore',
   85: 'I Love You Lord',
   86: 'We Love You with the Love of the Lord',
   87: 'I Stand in Awe',
   88: 'I Want Jesus to Walk with Me',
   89: 'I Want to Know Christ',
   90: 'I Will Call upon the Lord',
   92: 'I\'m Happy Today',
   93: 'I\'ve Been Crucified with Christ',
   94: 'I\'ve Got Peace Like a River',
   95: 'I\'ve Got the Joy',
  100: 'Jesus Is Lord',
  101: 'Jesus Keep Me Near the Cross (New)',
  102: 'Jesus Let Us Come to Know You',
  104: 'Jesus, Name Above All Names',
  114: 'Livin\' on the Lord\'s Side',
  115: 'Lord Be There',
  116: 'Lord Has a Will',
  117: 'Lord We Lift Your Name on High',
  121: 'Love, Love, Love, Love',
  124: 'Majesty',
  125: 'Make Me a Servant',
  128: 'May I Call You Father',
  133: 'On Bended Knee',
  135: 'Pass It On',
  136: 'Pierce My Ear',
  137: 'Praise the Name of Jesus',
  141: 'Rejoice in the Lord Always',
  142: 'Restore My Spirit Lord',
  146: 'Seek Ye First',
  150: 'Sing Hallelujah to the Lord',
  151: 'Someday',
  152: 'Soon and Very Soon',
  153: 'Steadfast Love of the Lord',
  154: 'Step by Step',
  156: 'Teach Me, Lord, to Wait',
  163: 'They\'ll Know We Are Christians',
  164: 'This Is the Day',
  166: 'Thy Word',
  169: 'Unto Thee, O Lord',
  170: 'Victory Chant',
  171: 'We Bow Down',
  174: 'We Shall Assemble',
  175: 'We Will Glorify',
  182: 'Wonderful, Wonderful',
  183: 'Worthy Is the Lamb',
  184: 'You Are the Song that I Sing',
}

# print(gvbcSongBookList)
print(gvbcSongBookList[random.randint(0, len(gvbcSongBookList) - 1)])
